# These are supported funding model platforms

github: [theriturajps] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: riturajps
open_collective: riturajps
ko_fi: riturajps
